sudo: required
services: 
  - docker
script:
  - docker build -t shreekarhegde/frontend ./frontend
  - docker build -t shreekarhegde/nginx ./nginx
  - docker build -t shreekarhegde/api ./api  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shreekarhegde/frontend
  - docker push shreekarhegde/nginx
  - docker push shreekarhegde/api

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'reddit'
  env: 'Reddit-env-1'
  bucket_name: 'elasticbeanstalk-ap-south-1-047565902808'
  bucket_path: 'reddit'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY