sudo: required
services: 
  - docker
script:
  - docker build -t shreekarhegde/reddit .

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'reddit'
  env: 'Reddit-env'
  bucket_name: 'elasticbeanstalk-us-east-2-047565902808'
  bucket_path: 'reddit'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY