sudo: required
services: 
  - docker
jobs:
  include:
    - stage: Build App
      script: docker build -t shreekarhegde/frontend:latest ./frontend
      script: docker build -t shreekarhegde/api:latest ./api  
    - stage: Push App
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin && docker push shreekarhegde/frontend:latest
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin && docker push shreekarhegde/api:latest

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'reddit'
  env: 'Reddit-env-1'
  bucket_name: 'elasticbeanstalk-ap-south-1-047565902808'
  bucket_path: 'reddit'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY